import { describe, it, expect } from "vitest";
import {
	xhsSign,
	generateB1,
	b1FromFingerprint,
	xhsQueryEscape,
	decodeCustomBase64,
	md5Hex,
	crc32JsInt,
	type B1Fingerprint,
	type SignRandomOverride,
} from "../src/rednote/sign";

// ---------------------------------------------------------------------------
// Golden vectors generated by running the ACTUAL xhshow algorithm (Cloxl/xhshow
// master, the signing library MediaCrawler delegates to) in Python with fixed
// randomness (seed=2882400001, timeOffset=17, sequence=42, windowProps=1100).
// The TS port must reproduce them byte-for-byte.
// ---------------------------------------------------------------------------

const A1 = "18ab1e5ce487139a3b7f9403557a0a11a52cef1b52";
const NOW_MS = 1764896636081;
const FIXED: SignRandomOverride = {
	seed: 2882400001,
	timeOffset: 17,
	sequence: 42,
	windowPropsLength: 1100,
};

const FIXED_FP: B1Fingerprint = {
	x33: "0",
	x34: "0",
	x35: "0",
	x36: "7",
	x37: "0|0|0|0|0|0|0|0|0|1|0|0|0|0|0|0|0|0|1|0|0|0|0|0",
	x38: "0|0|1|0|1|0|0|0|0|0|1|0|1|0|1|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0",
	x39: 0,
	x42: "3.4.4",
	x43: "742cc32c",
	x44: "1764896636081",
	x45: "__SEC_CAV__1-1-1-1-1|__SEC_WSA__|",
	x46: "false",
	x48: "",
	x49: "{list:[],type:}",
	x50: "",
	x51: "",
	x52: "",
	x82: "_0x17a2|_0x1954",
};

const EXPECTED_B1 =
	"I38rHdgsjopgIvesdVwgIC+oIELmBZ5e3VwXLgFTIxS3bqwErFeexd0ekncAzMFYnqthIhJeDBMDKutRI3KsYorWHPtGrbV0P9WfIi/eWc6eYqtyQApPI37ekmR6QL+5Ii6sdnoeSfqYHqwl2qt5B0DoIx+PGDi/sVtkIxdsxuwr4qtiIhuaIE3e3LV0I3VTIC7e0utl2ADmsLveDSKsSPw5IEvsiVtJOqw8BuwfPpdeTFWOIx4TIiu6ZPwrPut5IvlaLbgs3qtxIxes1VwHIkumIkIyejgsY/WTge7eSqte/D7sDcpipedeYrDtIC6eDVw2IENsSqtlnlSuNjVtIvoekqt3cZ7sVo4gIESyIEle+AFDI3EPKI8BIiWIZPwAIvGj4sesYINsxVwSIC7ef96e0fhPIive6WrS8qwUIE7s1f0s6WAeiVtwpjKeYqw9Iv8nz/3efqwvg9/sWVw8IxI2I38isqwZgVtI4LTjoAve6peeYqwxIvAeS0Os1DZiIi7sjbos3amyIv6sdqwaICmygVtxgVw4IE7sVVtFIiAsiqtSIENsdutSHuwPnVtdIxkhIvVr27lk2Ive1utCIEDtIkJeYut4bYRtn/0ejgI7Ih4s2uwfJPwSI35skqwWGD5s6WAs3phwIhos3fOs3utscPwaICJsWPw5IiJekeqLICKejd/sfPtUIx7sxuwD4BYaIhQgIv5s1M6e6gvsiLdedVtsIkYTI3ilJutpIxElIEvsxbr38W==";

const GET_URI = "/api/sns/web/v2/note/collect/page";
const GET_DATA = { user_id: "5a89c2c39e52e17b3b7f9403c", num: 30, cursor: "" };
const EXPECTED_GET_XS =
	"XYS_2UQhPsHCH0c1PUhMHjIj2erjwjQhyoPTqBPT49pjHjIj2eHjwjQgynEDJ74AHjIj2ePjwjQTJdPIPAZlg94aGLTlGFSVySSQn0mm2LTrzemk8eQeqgp+/eSazApnqDTG2bDAJnuUy0mOnbStJAS/tAHMcg81wrRPPdS8qMzsweH9cMG9a/bnyeYHPML3pBi3P/Qa89pl2L8I4AzF+Flk//pLzgH9JFRgLFlO4BMY8LzjaDSH+FRFzrQky7SaG9M6a/msJemaJFzO+ezePDE38/qEaDr62f+aP9SzNFzE+9YeanS0JdiUzjTya/YgagP9+94AngzH4MHRHjIj2ecjwjQ6GfkSG7cjKc==";
const EXPECTED_XS_COMMON =
	"2UQAPsHC+aIjqArjwjHjNsQhPsHCH0rjNsQhPaHCH0c1PUhMHjIj2eHjwjQgynEDJ74AHjIj2ePjwjQhyoPTqBPT49pjHjIj2ecjwjHFN0W9N0ZjNsQh+aHCH0rhGnHl8/p08/ch+ArAwnrAG04fw/cIPALM+9rIG/rlG/LUG9pfPnHMPjHVHdW9H0ijHjIj2eqjwjHjNsQhwsHCHDDAwoQH8B4AyfRI8FS98g+Dpd4daLP3JFSb/BMsn0pSPM87nrldzSzQ2bPAGdb7zgQB8nph8emSy9E0cgk+zSS1qgzianYt8Lzs/LzN4gzaa/+NqMS6qS4HLozoqfQnPbZEp98QyaRSp9P98pSl4oSzcgmca/P78nTTL08z/sVManD9q9z1J9p/8db8aob7JeQl4epsPrz6agW3Lr4ryaRApdz3agYDq7YM47HFqgzkanYMGLSbP9LA/bGIa/+nprSe+9LI4gzVPDbrJg+P4fprLFTALMm7+LSb4d+kpdzt/7b7wrQM498cqBzSpr8g/FSh+bzQygL9nSm7qSmM4epQ4flY/BQdqA+l4oYQ2BpAPp87arS34nMQyFSE8nkdqMD6pMzd8/4SL7bF8aRr+7+rG7mkqBpD8pSUzozQcA8Szb87PDSb/d+/qgzVJfl/4LExpdzQ4fRSy7bFP9+y+7+nJAzdaLp/2LSbJBL3cL8ra/+bLrTQwrQQyp4QnSm7cLS9z9iFq9pAnLSwq7Yn4M+QcA4S80D98/mfybmQyg8S+S4ULAYl4MpQz/4APnGIqA8gcnpkpdz7qBkN8pSl4ASQ40Y12juA8n8l478dwaRApM87wrSha/QQPAYkq7b7nf4n4rDF/bzxJFb98/8I8np8qg4hag8m8pPI/7PlzbkkanD7q9kjJ7PAGnMEagG9q9zl49bQc9ME8M8F2B4n4AzQz/4ApS8FzDSkcg+kqgz/aLpwq9zM4b+H4g4cJS8F8rShy9YQ4S8UP04VyAQQ4fLl4gzeaLpr4rS3afp84gcFGSSa4Bh6PBpx8FD7anWFqAQM498tLo4/a/PMq9Tl4M4ozepA+S4mqA+Iyo4QyBRAP98OqA+M4o+0Lo4YaL+tqM4c4ApQyLkSy9pl/rSea9px8sRA8SmFpLSh+7+h4g4r+rQ8GLSiLn4Q40pAPLF98/8d4d+k/BzS8b8FqFS3npzQP9SVadpFqrShznlQzg8A2BQUPAYgO/FjNsQhwaHCP/GA+/Z7PeD9waIj2erIH0iINsQhP/rjwjQ1J7QTGnIjKc==";

const POST_URI = "/api/sns/web/v1/feed";
const POST_DATA = {
	source_note_id: "66fad51c000000001b0224b8",
	image_formats: ["jpg", "webp", "avif"],
	extra: { need_body_topic: 1 },
	xsec_source: "pc_collect",
	xsec_token: "AB3rO-QopW5sgrJ41GwN01WCXh6yWPxjSoFI9D5JIMgKw=",
};
const EXPECTED_POST_XS =
	"XYS_2UQhPsHCH0c1PUhMHjIj2erjwjQhyoPTqBPT49pjHjIj2eHjwjQgynEDJ74AHjIj2ePjwjQTJdPIPAZlg94aGLTlGFSVySSQn0mm2LTrzemk8eQeqgp+/eSazApnqDTG2bSn8BuUyfEYLFE8PnYbp/8nJg81wrRPPdS8qMzsweH9cMG9a/bnyeYHPML3pBi3P/Qa89pl2L8I4AzF+Flk//pLzgH9JFRgLFlO4BMY8LzjaDSH+FRFzrQky7SaG9M6a/msJemaJFzO+ezePDE38/qEaDr62f+aP9SzNFzE+9YeaniEwnbFGn8OabLIJLQ8qr8Ua7SiaBuRHjIj2ecjwjQ6GfkSG7cjKc==";

describe("md5Hex", () => {
	it("matches RFC 1321 known vectors", () => {
		expect(md5Hex("")).toBe("d41d8cd98f00b204e9800998ecf8427e");
		expect(md5Hex("a")).toBe("0cc175b9c0f1b6a831c399e269772661");
		expect(md5Hex("abc")).toBe("900150983cd24fb0d6963f7d28e17f72");
		expect(md5Hex("message digest")).toBe("f96b697d7cb7938d525a2f31aaf161d0");
		expect(md5Hex("abcdefghijklmnopqrstuvwxyz")).toBe("c3fcd3d76192e4007dfb496cca67e13b");
		expect(
			md5Hex("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"),
		).toBe("d174ab98d277d9f5a5611c2c9f419d9f");
		expect(md5Hex("12345678901234567890123456789012345678901234567890123456789012345678901234567890")).toBe(
			"57edf4a22be3c955ac49da2e2107b67a",
		);
	});
});

describe("crc32JsInt", () => {
	it("is a signed 32-bit value with JS charCode semantics", () => {
		const v = crc32JsInt(EXPECTED_B1);
		expect(Number.isInteger(v)).toBe(true);
		expect(v).toBeGreaterThanOrEqual(-2147483648);
		expect(v).toBeLessThanOrEqual(2147483647);
		// (-1 ^ c ^ poly) with c = 0xFFFFFFFF for the empty input -> 0xEDB88320 signed
		expect(crc32JsInt("")).toBe(-306674912);
	});
});

describe("b1 generation (xhshow RC4 pipeline)", () => {
	it("reproduces the xhshow golden vector for a fixed fingerprint", () => {
		expect(b1FromFingerprint(FIXED_FP)).toBe(EXPECTED_B1);
	});

	it("generateB1 produces a non-empty custom-base64 string", () => {
		const b1 = generateB1(NOW_MS);
		expect(b1.length).toBeGreaterThan(100);
		expect(b1).toMatch(/^[A-Za-z0-9+/]+=*$/);
	});
});

describe("xhsSign golden vectors (xhshow parity)", () => {
	it("GET collect/page matches the xhshow-computed signature", () => {
		const sign = xhsSign(GET_URI, "GET", GET_DATA, A1, EXPECTED_B1, NOW_MS, FIXED);
		expect(sign["X-S"]).toBe(EXPECTED_GET_XS);
		expect(sign["X-T"]).toBe(String(NOW_MS));
		expect(sign["x-s-common"]).toBe(EXPECTED_XS_COMMON);
	});

	it("POST feed matches the xhshow-computed signature", () => {
		const sign = xhsSign(POST_URI, "POST", POST_DATA, A1, EXPECTED_B1, NOW_MS, FIXED);
		expect(sign["X-S"]).toBe(EXPECTED_POST_XS);
		expect(sign["X-T"]).toBe(String(NOW_MS));
	});
});

describe("xhsSign structural properties (no fixed randomness)", () => {
	const sign = xhsSign(GET_URI, "GET", GET_DATA, A1, EXPECTED_B1);

	it("X-S carries the XYS_ prefix and decodable envelope", () => {
		expect(sign["X-S"]).toMatch(/^XYS_/);
		// Envelope body is custom-base64; decode and check the JSON template.
		const json = decodeCustomBase64(sign["X-S"].slice(4));
		const parsed = JSON.parse(json) as Record<string, string>;
		expect(parsed["x0"]).toBe("4.3.5");
		expect(parsed["x1"]).toBe("xhs-pc-web");
		expect(parsed["x2"]).toBe("Windows");
		expect(parsed["x4"]).toBe("object");
		expect(parsed["x3"]).toMatch(/^mns0301_[A-Za-z0-9+/=]+$/);
	});

	it("x-s-common decodes to the s0..x11 structure", () => {
		const parsed = JSON.parse(decodeCustomBase64(sign["x-s-common"])) as Record<string, unknown>;
		expect(parsed["s0"]).toBe(5);
		expect(parsed["x5"]).toBe(A1);
		expect(parsed["x8"]).toBe(EXPECTED_B1);
		expect(parsed["x9"]).toBe(crc32JsInt(EXPECTED_B1));
		expect(parsed["x11"]).toBe("normal");
	});

	it("X-T is the current epoch ms and traceid is 16 hex chars", () => {
		const before = Date.now();
		const s = xhsSign(GET_URI, "GET", GET_DATA, A1, EXPECTED_B1);
		const after = Date.now();
		const xt = Number(s["X-T"]);
		expect(xt).toBeGreaterThanOrEqual(before);
		expect(xt).toBeLessThanOrEqual(after);
		expect(s["X-B3-Traceid"]).toMatch(/^[0-9a-f]{16}$/);
	});

	it("empty b1 falls back to local synthesis (x-s-common still consistent)", () => {
		const s = xhsSign(GET_URI, "GET", GET_DATA, A1, "");
		const parsed = JSON.parse(decodeCustomBase64(s["x-s-common"])) as Record<string, unknown>;
		expect(parsed["x5"]).toBe(A1);
		const b1 = String(parsed["x8"]);
		expect(b1.length).toBeGreaterThan(100);
		expect(parsed["x9"]).toBe(crc32JsInt(b1));
	});
});

describe("xhsQueryEscape (matches Python quote(safe=','))", () => {
	it("keeps commas raw and unreserved chars intact", () => {
		expect(xhsQueryEscape("a,b")).toBe("a,b");
		expect(xhsQueryEscape("abc123")).toBe("abc123");
		expect(xhsQueryEscape("x-y.z~_w")).toBe("x-y.z~_w");
	});
	it("escapes = / ! * ' ( ) and non-ASCII like Python quote", () => {
		expect(xhsQueryEscape("a=b")).toBe("a%3Db");
		expect(xhsQueryEscape("a/b")).toBe("a%2Fb");
		expect(xhsQueryEscape("a!b*c")).toBe("a%21b%2Ac");
		expect(xhsQueryEscape("a'b(d)e")).toBe("a%27b%28d%29e");
		expect(xhsQueryEscape("+ ")).toBe("%2B%20");
	});
});
